### ISSUE TITLE
Exception at startup on Gigalixir

### ISSUE THREAD

**Issue by petelacey** [bitcrowd/chromic_pdf#248]
Everything works as advertised, but I get an exception at startup that I'm curious about.

I have installed headless chrome on Gigalixir using this buildpack: https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-google-chrome.

I have a bog standard implementation of ChromicPDF in my Phoenix 1.6 application.

```elixir
children = [
  {ChromicPDF, [discard_stderr: false]}
]
opts = [strategy: :one_for_one, name: Readyroom.Supervisor]
Supervisor.start_link(children, opts)
```
When I deploy the app (that is, start it up), I get the following in my logs:

```
May 10 13:31:52 web.1  | [0510/203152.270745:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory 
May 10 13:31:53 web.1  | 20:31:52.778 [info] Tzdata has updated the release from 2021e to 2023c 
May 10 13:31:53 web.1  | [0510/203152.794833:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory 
May 10 13:31:53 web.1  | [0510/203152.794924:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory 
May 10 13:31:53 web.1  | [0510/203152.962836:ERROR:zygote_host_impl_linux.cc(273)] Failed to adjust OOM score of renderer with pid 136: Permission denied (13) 
May 10 13:31:53 web.1  |  
May 10 13:31:53 web.1  | DevTools listening on ws://[127.0.0.1](https://my.papertrailapp.com/systems/Staging/events?q=%22127.0.0.1%22&focus=1593053244161187843&selected=1593053244161187843):9222/devtools/browser/d1471ef4-5134-4181-bf28-51cf718af0ec 
May 10 13:31:53 web.1  | [0510/203153.234083:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable. 
May 10 13:31:53 web.1  | [0510/203153.454865:ERROR:zygote_host_impl_linux.cc(273)] Failed to adjust OOM score of renderer with pid 142: Permission denied (13) 
May 10 13:31:53 web.1  | Failed to create /app/.cache for shader cache (Permission denied)---disabling. 
May 10 13:31:53 web.1  | [0510/203153.597692:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process. 
May 10 13:31:54 web.1  | [0510/203154.629641:ERROR:zygote_host_impl_linux.cc(273)] Failed to adjust OOM score of renderer with pid 187: Permission denied (13) 
May 10 13:31:54 web.1  | 20:31:54.596 [error] Task #PID<0.636.0> started from #PID<0.635.0> terminating 
May 10 13:31:54 web.1  | ** (ChromicPDF.Browser.ExecutionError) Timeout in Channel.run_protocol/3! 
May 10 13:31:54 web.1  |  
May 10 13:31:54 web.1  | The underlying GenServer.call/3 exited with a timeout. This happens when the browser was 
May 10 13:31:54 web.1  | not able to complete the current operation (= PDF print job) within the configured 
May 10 13:31:54 web.1  | 5000 milliseconds. 
May 10 13:31:54 web.1  |  
May 10 13:31:54 web.1  | If you are printing large PDFs and expect long processing times, please consult the 
May 10 13:31:54 web.1  | documentation for the `timeout` option of the session pool. 
May 10 13:31:54 web.1  |  
May 10 13:31:54 web.1  | If you are *not* printing large PDFs but your print jobs still time out, this is likely a 
May 10 13:31:54 web.1  | bug in ChromicPDF. Please open an issue on the issue tracker. 
May 10 13:31:54 web.1  |  
May 10 13:31:54 web.1  | --- 
May 10 13:31:54 web.1  |  
May 10 13:31:54 web.1  | Current protocol: 
May 10 13:31:54 web.1  |  
May 10 13:31:54 web.1  | %ChromicPDF.Protocol{ 
May 10 13:31:54 web.1  |   steps: [ 
May 10 13:31:54 web.1  |     await: &ChromicPDF.SpawnSession.page_enabled/2, 
May 10 13:31:54 web.1  |     call: &ChromicPDF.ResetTarget.reset_history/2, 
May 10 13:31:54 web.1  |     await: &ChromicPDF.ResetTarget.history_reset/2, 
May 10 13:31:54 web.1  |     call: &ChromicPDF.ResetTarget.blank/2, 
May 10 13:31:54 web.1  |     await: &ChromicPDF.ResetTarget.blanked/2, 
May 10 13:31:54 web.1  |     await: &ChromicPDF.ResetTarget.fsl_after_blank/2, 
May 10 13:31:54 web.1  |     output: &ChromicPDF.SpawnSession.output/1 
May 10 13:31:54 web.1  |   ], 
May 10 13:31:54 web.1  |   state: %{ 
May 10 13:31:54 web.1  |     :__protocol__ => ChromicPDF.SpawnSession, 
May 10 13:31:54 web.1  |     :discard_stderr => false, 
May 10 13:31:54 web.1  |     :ignore_certificate_errors => false, 
May 10 13:31:54 web.1  |     :last_call_id => 6, 
May 10 13:31:54 web.1  |     :name => "[FILTERED]", 
May 10 13:31:54 web.1  |     :offline => false, 
May 10 13:31:54 web.1  |     :unhandled_runtime_exceptions => "[FILTERED]", 
May 10 13:31:54 web.1  |     "browserContextId" => "[FILTERED]", 
May 10 13:31:54 web.1  |     "sessionId" => "5A0A13F31D49440DC3E696728B9D464C", 
May 10 13:31:54 web.1  |     "targetId" => "866DAC95CFEFDC55F41B10EFAC1E6AEB" 
May 10 13:31:54 web.1  |   } 
May 10 13:31:54 web.1  | } 
May 10 13:31:54 web.1  |  
May 10 13:31:54 web.1  |     (chromic_pdf 1.9.0) lib/chromic_pdf/pdf/browser/channel.ex:23: ChromicPDF.Browser.Channel.run_protocol/3 
May 10 13:31:54 web.1  |     (chromic_pdf 1.9.0) lib/chromic_pdf/pdf/browser/session_pool.ex:154: ChromicPDF.Browser.SessionPool.do_init_worker/1 
May 10 13:31:54 web.1  |     (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2 
May 10 13:31:54 web.1  |     (elixir 1.14.2) lib/task/supervised.ex:34: Task.Supervised.reply/4 
May 10 13:31:54 web.1  |     (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3 
May 10 13:31:54 web.1  | Function: #Function<0.100967843/0 in ChromicPDF.Browser.SessionPool.init_worker/1> 
May 10 13:31:54 web.1  |     Args: []
```
Eventually, things must get straightened out, since I am able to generate (small) PDFs and there are no other errors.

Note, there's a reference to "papertrailapp.com" in those logs. Papertrail is my log management tool. I'm not sure if it's meaningful that their URL is in the Chrome error output. Probably not, but...

Anyway, are exceptions like this at startup to be expected? Is there something I can do to prevent this.

Thanks for the awesome tool.

**Comment by maltoe** [comment]
Hey @petelacey 

issues at startup aren't uncommon, unfortunately, see for example #160. In some environments Chrome just seems be a bit sluggish when first launched, which is why we added the [`warm_up/1`](https://hexdocs.pm/chromic_pdf/ChromicPDF.html#warm_up/1) function. You could try calling that before you start your application supervision tree, or alternatively, if you don't want to go through Elixir for this, something like `chrome --dump-dom about:blank` should do. That _might_ fix the exceptions, but no guarantees.

> Eventually, things must get straightened out

Exactly. The exception you're seeing is when chromic tries to spawn sessions (= tabs) in the browser and initialize them. If they die, supervision takes care of creating new ones.

**Comment by petelacey** [comment]
I should have noticed #160 before creating this issue. Sorry about that.

In any event, adding the `warm_up` call do `application.ex` did indeed eliminate the error. There are still a fair number of ugly warning being spat out, but they all seem to stem from the being constrained by the docker container that Chrome is running in. Unfortunately, because I'm deploying to a PaaS, I have no influence over this container. It might be time to investigate moving to fly.io.

For now, though, the warnings don't seem to be impacting anything and I am able to generate PDFs, so please consider this issue closed, and thanks again.
