### ISSUE TITLE
Will this work with msEdge and Google Chrome for Testing?

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [bitcrowd/chromic_pdf#307]
Hi,

I'm trying this **_chromic_pdf_** on WIndows10 with **`Google Chrome for Testing`** as well as **`msEdge`**.

I have downloaded a local copy of Chrome for Testing, and stored the Chrome.exe location in my system PATH: C:\Tools\chrome-win64\Chrome.exe

I am unable to load beyond this error:

```
01:04:41.145 [error] GenServer #PID<0.2959.0> terminating
** (ChromicPDF.Connection.ConnectionLostError) Chrome has stopped or was terminated by an external program.

If this happened while you were printing a PDF, this may be a problem with Chrome itelf.
If this happens at startup and you are running inside a Docker container with a Linux-based
image, please see the "Chrome Sandbox in Docker containers" section of the documentation.

Either way, to see Chrome's error output, configure ChromicPDF with the option

    discard_stderr: false

    (chromic_pdf 1.15.2) lib/chromic_pdf/pdf/connection/local.ex:53: ChromicPDF.Connection.Local.handle_info/2
    (stdlib 5.2.3) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2.3) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.458662647.298582017.191736>, :port, #Port<0.8>, :normal}
```

For msEdge (also a Chromium based browser), which comes bundled on windows 10,11 and windows-server 2019+, I tried adding msedge.exe to `@default_executables`

```
@default_executables [
    "chromium-browser",
    "chromium",
    "chrome.exe",
    "msedge.exe",
    "google-chrome",
    "/usr/bin/chromium-browser",
    "/usr/bin/chromium",
    "/usr/bin/google-chrome",
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Chromium.app/Contents/MacOS/Chromium"
  ]
  ```
  
  Please can you guide on how to troubleshoot the above two scenarios.

Thanks

**Comment by andreasknoepfle** [comment]
You can pass in a custom `chrome_executable` option to specify an alternative chrome path (e.g. in your application.ex as described here):

https://hexdocs.pm/chromic_pdf/ChromicPDF.html#module-custom-command-line-switches

But I doubt that `msEdge` will work, since we rely on command line options to pass into chrome, which will most likely be different for msEdge.  But adding the `chrome_executable: "C:\Tools\chrome-win64\Chrome.exe"` will most likely work. 
One note here is that most contributors to this codebase work with Linux or MacOS, so the Windows support might be somewhat less often tested. But we already heard of users being successful with it.

**Comment by CharlesOkwuagwu** [comment]
Thanks for your response.

I have applied ` chrome_executable: "C:\Tools\chrome-win64\Chrome.exe"` and it comes up with the same errors:
```
09:41:25.298 [error] GenServer #PID<0.561.0> terminating
** (ChromicPDF.Connection.ConnectionLostError) Chrome has stopped or was terminated by an external program.

If this happened while you were printing a PDF, this may be a problem with Chrome itelf.
If this happens at startup and you are running inside a Docker container with a Linux-based
image, please see the "Chrome Sandbox in Docker containers" section of the documentation.

Either way, to see Chrome's error output, configure ChromicPDF with the option

    discard_stderr: false

    (chromic_pdf 1.15.2) lib/chromic_pdf/pdf/connection/local.ex:53: ChromicPDF.Connection.Local.handle_info/2
    (stdlib 5.2.3) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2.3) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.2340099235.2257846276.60362>, :port, #Port<0.7>, :normal}
```

**Comment by andreasknoepfle** [comment]
Have you tried running the downloaded chrome yourself? Does it run? 

If you run chromic_pdf, do you see the instance of chrome coming up in the task manager? 

The message that you are seeing is chromic_pdf getting a message from the [port](https://hexdocs.pm/elixir/Port.html) that the chrome process died.

**Comment by andreasknoepfle** [comment]
To me it looks more like chrome crashes and less like it is not found, since I would expect a different error in that case (maybe experiment by setting the `chome_executable` to something not existing to see if that would return a different error.

**Comment by maltoe** [comment]
Going to close this for now. @CharlesOkwuagwu please re-open if you have further questions.

**Comment by CharlesOkwuagwu** [comment]
This simple config launches msEdge

```
port =
      Port.open(
        {:spawn_executable, "C:\\Windows\\System32\\cmd.exe"},
        [
          :binary,
          :exit_status,
          :stderr_to_stdout,
          :hide,
          {:args,
           [
             "/c",
             "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
             "--remote-debugging-port=9222",
             "--headless"
           ]}
        ]
      )
```

**Comment by CharlesOkwuagwu** [comment]
@maltoe 

in my application.ex

```
{
          ChromicPDF,
          chrome_executable: "C:/Tools/ChromeFT/chrome-win64/chrome.exe",
          on_demand: true,
          session_pool: [size: 1, max_size: 2],
          discard_stderr: false,
          connection: [user_data_dir: Path.expand("_data/chromium-profile"), mode: :pipe],
          chrome_args: [
            "--enable-logging=stderr",
            "--v=1",
            "--headless=new",
            "--disable-gpu",
            "--no-first-run",
            "--no-default-browser-check",
            "--disable-features=RendererCodeIntegrity"
          ],
          print_to_pdf: [
            print_background: true,
            prefer_css_page_size: true
          ]
        }
```

```
 html = "<html><body><h1>OK PDF</h1></body></html>"
"<html><body><h1>OK PDF</h1></body></html>"

nil
 ChromicPDF.print_to_pdf({:html, html}, print_to_pdf: [path: "_media/test.pdf"])
[21:32:52.949] GenServer #PID<0.844.0> terminating
** (ChromicPDF.Connection.ConnectionLostError) Chrome has stopped or was terminated by an external program.

If this happened while you were printing a PDF, this may be a problem with Chrome itelf.
If this happens at startup and you are running inside a Docker container with a Linux-based
image, please see the "Chrome Sandbox in Docker containers" section of the documentation.

Either way, to see Chrome's error output, configure ChromicPDF with the option

    discard_stderr: false

    (chromic_pdf 1.17.0) lib/chromic_pdf/pdf/connection/local.ex:49: ChromicPDF.Connection.Local.handle_info/2
    (stdlib 6.2.2.1) gen_server.erl:2345: :gen_server.try_handle_info/3
    (stdlib 6.2.2.1) gen_server.erl:2433: :gen_server.handle_msg/6
    (stdlib 6.2.2.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.3794172526.298582019.73233>, :port, #Port<0.143>, :normal}
State: %{port: #Port<0.143>, channel_pid: #PID<0.843.0>, tokenizer: []}
** (exit) exited in: NimblePool.checkout(#PID<0.846.0>)
    ** (EXIT) shutdown
    (nimble_pool 1.1.0) lib/nimble_pool.ex:518: NimblePool.exit!/3
    (chromic_pdf 1.17.0) lib/chromic_pdf/pdf/browser/session_pool.ex:54: ChromicPDF.Browser.SessionPool.checkout!/3
    (chromic_pdf 1.17.0) lib/chromic_pdf/api.ex:82: anonymous fn/3 in ChromicPDF.API.chrome_export/4
    (chromic_pdf 1.17.0) lib/chromic_pdf/api/telemetry.ex:10: anonymous fn/2 in ChromicPDF.Telemetry.with_telemetry/3
    (telemetry 1.3.0) c:/Projects/gateway/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
    (chromic_pdf 1.17.0) lib/chromic_pdf/supervisor.ex:114: ChromicPDF.Supervisor.with_on_demand_browser/2
    iex:3: (file)

```

**Comment by maltoe** [comment]
Hi @CharlesOkwuagwu 

that error indicates Chrome has crashed. As you have `discard_stderr: false` in your options already, I'm assuming you're seeing some logs?

I'm sorry I can't help you much here, there's a multitude of reasons for why Chrome could crash, it's quite a complex piece of tech.

Good luck!
